/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WomenHealthRouteImport } from './routes/women-health'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as NearbyRouteImport } from './routes/nearby'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CheckRouteImport } from './routes/check'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'

const WomenHealthRoute = WomenHealthRouteImport.update({
  id: '/women-health',
  path: '/women-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyRoute = NearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckRoute = CheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/check': typeof CheckRoute
  '/history': typeof HistoryRoute
  '/nearby': typeof NearbyRoute
  '/reminders': typeof RemindersRoute
  '/scan': typeof ScanRoute
  '/services': typeof ServicesRoute
  '/women-health': typeof WomenHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/check': typeof CheckRoute
  '/history': typeof HistoryRoute
  '/nearby': typeof NearbyRoute
  '/reminders': typeof RemindersRoute
  '/scan': typeof ScanRoute
  '/services': typeof ServicesRoute
  '/women-health': typeof WomenHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/check': typeof CheckRoute
  '/history': typeof HistoryRoute
  '/nearby': typeof NearbyRoute
  '/reminders': typeof RemindersRoute
  '/scan': typeof ScanRoute
  '/services': typeof ServicesRoute
  '/women-health': typeof WomenHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/alerts'
    | '/auth'
    | '/check'
    | '/history'
    | '/nearby'
    | '/reminders'
    | '/scan'
    | '/services'
    | '/women-health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/alerts'
    | '/auth'
    | '/check'
    | '/history'
    | '/nearby'
    | '/reminders'
    | '/scan'
    | '/services'
    | '/women-health'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/alerts'
    | '/auth'
    | '/check'
    | '/history'
    | '/nearby'
    | '/reminders'
    | '/scan'
    | '/services'
    | '/women-health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  AlertsRoute: typeof AlertsRoute
  AuthRoute: typeof AuthRoute
  CheckRoute: typeof CheckRoute
  HistoryRoute: typeof HistoryRoute
  NearbyRoute: typeof NearbyRoute
  RemindersRoute: typeof RemindersRoute
  ScanRoute: typeof ScanRoute
  ServicesRoute: typeof ServicesRoute
  WomenHealthRoute: typeof WomenHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/women-health': {
      id: '/women-health'
      path: '/women-health'
      fullPath: '/women-health'
      preLoaderRoute: typeof WomenHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby': {
      id: '/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof NearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check': {
      id: '/check'
      path: '/check'
      fullPath: '/check'
      preLoaderRoute: typeof CheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  AlertsRoute: AlertsRoute,
  AuthRoute: AuthRoute,
  CheckRoute: CheckRoute,
  HistoryRoute: HistoryRoute,
  NearbyRoute: NearbyRoute,
  RemindersRoute: RemindersRoute,
  ScanRoute: ScanRoute,
  ServicesRoute: ServicesRoute,
  WomenHealthRoute: WomenHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
